### PR TITLE
Allow usage of free DeepL API (different base URL)

### PR DESCRIPTION
**Pull request by MichalCadecky**
First of all I'm sorry to start already with fork - I have read the contribution notice after I had been done with the change :/ Although the change is very trivial. There is already a pull request with similiar idea #8 but my approach is slightly different and I think it is better aligned with the original idea of keeping the `baseUrl` readonly.

If there is anything I could improve, please let me know.

### CODE REVIEW

**Comment by lecode-official** [comment]
Hi Michal,

I am really sorry that I am only answering now, I was on vacation this week and spend some quality time with my family.

You are right, I like your approach much better than overriding the `baseUrl`.

I hope you are not mad at me for being nitpicky, but I would really like to change the name of the parameter from `isFree` to `useFreeApi`, which is more in line with my general naming conventions. Also, the `baseUrl` should be `proApiBaseUrl` and `baseFreeUrl` should be `freeApiBaseUrl`. If you want to, I can merge your pull request make the adjustments afterwards.

**Comment by MichalCadecky** [comment]
Hi David,

no worries. Nice to hear someone is able to actually have a great time with family during this strange lockdown/quarantine times. I don't find your remarks nitpicky at all. I completely agree with them and I have updated the code accordingly. I am making all the changes via GitHub currently, so hopefully there is no typo causing compile errors.

Thanks for you great work.

**Comment by lecode-official** [comment]
Yes, this (and the previous) year have been crazy. I was happy to have some free time to spend with my son. I hope you have been doing fine and are staying healthy.

Thanks for the changes, everything looks good! I will merge the pull request now and try to get out a new release on NuGet as fast as possible.

**Comment by lecode-official** [comment]
Hi Michal,

I have just released a new version of DeepL.NET on NuGet including your contribution. If you have any problems, please let me know.

**Comment by MichalCadecky** [comment]
Hi David,

I have just replaced the modified source code with updated the NuGet and everything is working flawlessly. 

I have seen you also updated the DeepL.Cli (DeepL.Sample originally) project which I had completely missed with the change request. And obviously I had forgotten about the documentation as well (shame on me). Next time I will try to be more careful :)

And to your previous post - Fortunately yes, I have been doing fine. Hopefully you can say the same.

Anyways, thanks again for your work and for accepting my changes. DeepL.NET is very helpful tool and it saved me a lot of time!

**Comment by lecode-official** [comment]
I am happy to hear that (both that you are doing fine and that everything works flawlessly). That is absolutely no problem, I can not monitor changes to the DeepL API all the time, so I am dependent on and always thankful for issues and pull requests from users. This makes it so much easier to keep things up-to-date.

**Pull request merged**
