### PR TITLE
added missing )

### PR DESCRIPTION
**Pull request by mmattes**
Hi,

there is a ) missing in the sample of the readme.

### CODE REVIEW

**Comment by lecode-official** [comment]
Hi Markus,

again: thank you for your contribution. I will merge this pull request, but please add yourself to the CONTRIBUTORS.md, either in this pull request or the other.

**Comment by lecode-official** [comment]
Hi Markus,

are you still interested in this pull request? If not, then I would finish it for you. I would add you to the CONTRIBUTORS.md if that is okay with you.

**Comment by mmattes** [comment]
Hi David,

Thats okay for me If you do ot. I havent found the time to do so yet.

David Neumann <notifications@github.com> schrieb am Mi., 28. Okt. 2020,
10:38:

**Comment by lecode-official** [comment]
Hi Markus,

then I will merge your two requests now and add you to the CONTRIBUTORS.md. Thanks again for your help.

PS: Do you need the new language support immediately? If so I can publish a small release to NuGet. Otherwise I think I am going to wait until some more changes have accumulated.

**Comment by mmattes** [comment]
I dont need it immediately as i build my own local libary from source

David Neumann <notifications@github.com> schrieb am Fr., 30. Okt. 2020,
12:45:

**Pull request merged**
