### PR TITLE
Add parameter to DeeplClient to be able to overwrite the baseUrl

### PR DESCRIPTION
**Pull request by RaoulJacobs**

### CODE REVIEW

**Comment by lecode-official** [comment]
Hi Raoul,

thank you very much for your contribution. I have two minor problems with your pull request:

1. You have committed your Visual Studio configuration files, which should not be checked into the source code repository, because they are specific to you
2. You removed the `readonly` keyword from the `baseUrl` field, but it is still static, this means that when you have more than one instance of `DeepLClient`, each consecutive instance overrides the `baseUrl` of all existing instances

Michal Cadecky actually created a pull request just a short time after you solving the same problem. I think his solution is a bit more elegant. Instead of making it possible to change the `baseUrl` it has a flag that allows you to specify whether you want to use the free API tier. I hope you can understand that I will merge Michals pull request. I still want to honor your contribution and add you to the contributors list, if that is okay?

**Comment by RaoulJacobs** [comment]
Hi David

Sure thx for the feedback

**Comment by lecode-official** [comment]
Okay, then I'll close the pull request now.

**Comment by lecode-official** [comment]
Hi Raoul,

I have just released a new version of DeepL.NET on NuGet including the new constructor parameter `useFreeApi`. As promised, I have included you in the release notes and the contributors list. If you have any issues, please let me know.

**Comment by RaoulJacobs** [comment]
Super thx

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Pull request closed without merging**
